name: godot export

# Whenever a push is made to the master branch then run the job
on: 
  push:
    branches:
      - master

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game Job
    steps:
    - name: checkout
      uses: actions/checkout@v2.1.0
    - name: export game
      uses: firebelley/godot-export@v2.1.0
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.1/mono/Godot_v3.2.1-stable_mono_linux_headless_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.1/mono/Godot_v3.2.1-stable_mono_export_templates.tpz
        relative_project_path: ./
        base_version: 0.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
